# Generated by Django 3.0.8 on 2020-07-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='area',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.Area'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='school',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.School'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='university',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.University'),
        ),
    ]
