# Generated by Django 3.0.8 on 2020-07-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20200717_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='area',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.School'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.University'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
