# Generated by Django 3.0.8 on 2020-07-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_university_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='school',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='subscription.School'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='university',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='subscription.University'),
        ),
    ]
