# Generated by Django 3.0.8 on 2020-07-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('subscription', '0007_auto_20200717_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='universities.School'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='universities.University'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
