# Generated by Django 3.0.8 on 2020-07-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_schools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name_school']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name_university']},
        ),
        migrations.RenameField(
            model_name='university',
            old_name='initials',
            new_name='acronym',
        ),
        migrations.RemoveField(
            model_name='university',
            name='schools',
        ),
    ]
