# Generated by Django 3.0.8 on 2020-07-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20200717_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_name']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['university_name']},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='name_school',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='name_university',
            new_name='university_name',
        ),
    ]
